version: '3.6'
services:
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
  
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: ./kafka-docker
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock